### ISSUE TITLE
protoc_plugin should depend on newer dart_style

### ISSUE THREAD

**Issue by Gursewak-Uppal** [google/protobuf.dart#567]
Running "flutter pub get" in MyProject...

```
Because no versions of protoc_plugin match >20.0.0 <21.0.0 and protoc_plugin 20.0.0 depends on dart_style ^1.0.6, protoc_plugin ^20.0.0 requires dart_style ^1.0.6.
And because source_gen >=1.0.0 depends on dart_style ^2.0.0, protoc_plugin ^20.0.0 is incompatible with source_gen >=1.0.0.
So, because MyProject depends on both source_gen 1.2.1 and protoc_plugin ^20.0.0, version solving failed.
pub get failed (1; So, because MyProject depends on both source_gen 1.2.1 and protoc_plugin ^20.0.0, version solving failed.)
```

Process finished with exit code 1

**Comment by siloebb** [comment]
I think that the version in Pub is wrong? Let me test using override

**Comment by siloebb** [comment]
Using dependency override with I can use the pub get.
So I really think that there is an error in version published in the Pub


```
dependency_overrides:
  protoc_plugin:
    git:
      url: git@github.com:google/protobuf.dart.git
      path: protoc_plugin
```
